language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: HlrY8BzAt2OyyoVkTVBmQwoAf1sBGCJbZ0QjZ5DDB4+mFsy/wDMRU1jcICaQ5wFqUcmg4rqJVryh1AH7JF/nvSimCfcQ09SOEJFVzExZUJvJCH/znUIUDF8l+QQ3JzBZNs77Nm7uPGDFHB4vAYrq4Ipg0tK6C1H8rRJQtf7lL18=
